name: Windows 10 RDP with Ngrok

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup Ngrok
        run: |
          choco install ngrok -y
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok and show RDP address
        shell: powershell
        run: |
          Start-Process ngrok "tcp 3389" -WindowStyle Hidden
          Start-Sleep -Seconds 10
          $response = Invoke-RestMethod http://127.0.0.1:4040/api/tunnels
          $tcp = $response.tunnels | Where-Object { $_.proto -eq "tcp" }
          Write-Host "=============================="
          Write-Host "Your RDP Address:"
          Write-Host $tcp.public_url
          Write-Host "=============================="
          Start-Sleep -Seconds 21600

      - name: Enable RDP Access
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
