name: Win10 RDP Ngrok

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Start RDP via Ngrok
      shell: cmd
      run: |
        choco install ngrok -y
        ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ngrok tcp 3389 > ngrok.log &
        powershell -Command "Get-Content ngrok.log -Wait"
